name: Checks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  checks:
    runs-on: ubuntu-20.04
    if: "!contains(github.event.head_commit.message, 'chore: release')"
    steps:
    - name: Checkout 
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GH_TOKEN }}
    - name: Setup 
      uses: actions/setup-node@v3
      with:
        node-version: '18.14.2'
        cache: 'npm'
    - name: Install
      run: npm ci
    - name: Build
      run: npm run build
    - name: Test
      run: npm run test
    - name: Lint
      run: npm run lint
