name: Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GH_TOKEN }}
        fetch-depth: 0
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '18.13.0'
        registry-url: 'https://registry.npmjs.org'
    - name: Setup Git
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "Github Action"
    - name: Setup NPM
      run: echo //registry.npmjs.org/:_authToken=${NPM_TOKEN} > .npmrc
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    - name: Install
      run: npm ci
    - name: Build
      run: npm run build
    - name: Version
      run: npm run version
    - name: Changelog
      run: |
        npm run changelog
        git add CHANGELOG.md
        git commit -m "chore: changelog"
        git push --force
    - name: Publish
      run: npm run publish
    - name: Release
      run: npm run release
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
